# Create a new review
POST http://localhost:3333/api/reviews HTTP/1.1
Content-Type: application/json
User-id: 123

{
  "authorId": "asdasdasd",
  "text": "12312321",
  "taskId": "4553453"
}

###

# Get reviews
GET http://localhost:3333/api/reviews/tasks/4553453 HTTP/1.1

###

# Delete review
DELETE  http://localhost:3333/api/reviews/42b729e4-e002-4c05-9b58-f4fd6813683c HTTP/1.1

###
