#1 Create a new user
POST http://localhost:3333/api/user/register HTTP/1.1
Content-Type: application/json

{
  "userName": "Keks",
  "email": "test@test.ru",
  "city": "Москва",
  "password": "123456",
  "dateBirth": "2003-12-22",
  "role": "customer"
}
###

#2 Update user's password
PATCH http://localhost:3333/api/user/password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E4OTg1YjUyNjFmOGM5ZTJlYzI2MjMiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY2xpZW50IiwibmFtZSI6Iktla3MiLCJfaWQiOiI2M2E4OTg1YjUyNjFmOGM5ZTJlYzI2MjMiLCJpYXQiOjE2NzIwNDMyMjQsImV4cCI6MTY3MjA0MzgyNH0.00pcBnTD9Uq2SnHpJtUNWYyTobGtRgsrURBpIkkO_t8
Content-Type: application/json

{
  "email": "user@notfound.local",
  "currentPassword": "123456",
  "newPassword": "234567"
}
###
